nameOverride: ""

serviceAccount:
  annotations: {}
  name: secrets-store-csi-driver-provider-gcp

image:
  repository: us-docker.pkg.dev/secretmanager-csi/secrets-store-csi-driver-provider-gcp/plugin
  pullPolicy: IfNotPresent
  hash: sha256:68d388881ec9445a873763fe6a39f9a8276970ed7478fbc8776565d16667af1e

app: csi-secrets-store-provider-gcp

podAnnotations: {}

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi

priorityClassName: ""

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
