apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-id-config
  namespace: kube-system
immutable: false
data:
  config: >-
    {
      "audience":"//iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID",
      "credential_source":{
        "file":"/var/run/secrets/tokens/gcp-ksa/token",
        "format":{
          "type":"text"
        }
      },
      "subject_token_type":"urn:ietf:params:oauth:token-type:jwt",
      "token_info_url":"https://sts.googleapis.com/v1/introspect",
      "token_url":"https://sts.googleapis.com/v1/token",
      "type":"external_account",
      "universe_domain":"googleapis.com"
    }

---
# Separate deployment to manage actual driver debugging independent of node registrar and livenessprobe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-driver
  namespace: kube-system
spec:
  replicas: 1 # Keep single replica for debugging
  selector:
    matchLabels:
      app: debug-driver
  template:
    metadata:
      labels:
        app: debug-driver
    spec:
      serviceAccountName: secrets-store-csi-driver-provider-gcp
      initContainers:
        - name: chown-provider-mount
          image: busybox
          command:
            - chown
            - "1000:1000"
            - /etc/kubernetes/secrets-store-csi-providers
          volumeMounts:
            - mountPath: "/etc/kubernetes/secrets-store-csi-providers"
              name: providervol
      containers:
        - name: debug-driver
          image: debug-driver:latest # dlv debug image built locally
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /secrets-store-csi-driver-provider-gcp-codebase
              name: driver-volume
            - name: providervol
              mountPath: /etc/kubernetes/secrets-store-csi-providers
              mountPropagation: None
              readOnly: false
            - name: "gcp-ksa"
              mountPath: "/var/run/secrets/tokens/gcp-ksa"
              readOnly: true
              mountPropagation: None
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          env:
            - name: TARGET_DIR
              value: /etc/kubernetes/secrets-store-csi-providers
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/run/secrets/tokens/gcp-ksa/google-application-credentials.json
            - name: GAIA_TOKEN_EXCHANGE_ENDPOINT
              value: https://sts.googleapis.com/v1/token
      volumes:
        - name: driver-volume
          hostPath:
            path: # /path/to/your/secrets-store-csi-driver-provider-gcp/codebase/on/host
            type: Directory
        - name: providervol
          hostPath:
            path: /etc/kubernetes/secrets-store-csi-providers
        - name: "gcp-ksa"
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: # //iam.googleapis.com/projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
                  expirationSeconds: 172800
                  path: token
              - configMap:
                  name: workload-id-config
                  items:
                      - key: config
                        path: google-application-credentials.json
                  optional: false

---
# Service to connect dlv apis
apiVersion: v1
kind: Service
metadata:
  name: service-debug
  namespace: kube-system
spec:
  type: NodePort
  selector:
    app: debug-driver
  ports:
  - name: debug
    port: 30123
    targetPort: 30123
    nodePort: 30123
