apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "secrets-store-csi-driver-provider-gcp.clusterRoleName" . }}
  labels:
    {{- include "secrets-store-csi-driver-provider-gcp.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts/token
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
