nameOverride: ""

serviceAccount:
  annotations: {}
  name: secrets-store-csi-driver-provider-gcp

image:
  repository: us-docker.pkg.dev/secretmanager-csi/secrets-store-csi-driver-provider-gcp/plugin
  pullPolicy: IfNotPresent
  hash: sha256:183c92fbe7905ebe09ccec6496e91b7b615b1e88096576bc100d46fe97fe9770

app: csi-secrets-store-provider-gcp

podAnnotations: {}

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi

priorityClassName: ""

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
