nameOverride: ""

serviceAccount:
  annotations: {}
  name: secrets-store-csi-driver-provider-gcp

image:
  repository: us-docker.pkg.dev/secretmanager-csi/secrets-store-csi-driver-provider-gcp/plugin
  pullPolicy: IfNotPresent
  hash: sha256:c87cfa3e8be097c0034f136fb56e37d76966430b69223c12d179398ea0584576

app: csi-secrets-store-provider-gcp

podAnnotations: {}

resources:
  requests:
    cpu: 50m
    memory: 100Mi
  limits:
    cpu: 50m
    memory: 100Mi

priorityClassName: ""

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
