# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: e2e
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    # run daily @ 14:30 UTC against the default branch (main)
    - cron: "30 14 * * *"

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment:
      name: e2e-test
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: "Authenticate to Google Cloud via Workload Identity"
        uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
        with:
          workload_identity_provider: 'projects/735463103342/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'gh-e2e-runner@secretmanager-csi-build.iam.gserviceaccount.com'
      - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1
        with:
          project_id: "secretmanager-csi-build"
          install_components: 'gke-gcloud-auth-plugin'
      - name: Test
        run: |
          test/infra/runner.sh
        env:
          GKE_VERSION: RAPID
          SECRET_STORE_VERSION: main
